### PR TITLE
Basic 1616

### PR DESCRIPTION
**Pull request by sherakama**
- Consolidates private page test features
- Fixes broken tests in JSE
- Adds new remote for behat repo to use patched version
- Adds new tests via symlink to JSE

### CODE REVIEW

**Comment by sherakama** [comment]
@jbickar,

Please pass to @cjwest when complete.

**Comment by cjwest** [comment]
@sherakama : Would it be possible to have this PR merge into the JSE-Dev branch?

**Comment by sherakama** [comment]
@cjwest, I have no objection to what you want to do with this. Create yourself a PR or merge it on your machine.

**Comment by cjwest** [comment]
@sherakama , Ran successfully! Looks good!

**Pull request merged**
