### PR TITLE
Proposed re-factoring of linky-click structure to reduce duplication and...

### PR DESCRIPTION
**Pull request by sherakama**
... to take advantage of profiles and configurables

### CODE REVIEW

**Comment by sherakama** [comment]
@jbickar,

Here is a proposed restructure to the way the configuration files are set up.

Changes:
1. Created an includes directory were we will place all common assets across all testing
2. Created a mink and drupal include asset
3. Changed the default behat.yml to include the new common assets. They now need overrides.
4. Added the inclusion of behat.local.yml in behat.yml but also added it to .gitignore
5. behat.local.yml will use profiles to define custom settings for local or sites and will need to exist, even if empty.

In my behat.local.yml I have the following because I have a custom setup and drush alias.
```yaml
## Local development settings:
local:
  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://caw.su.dev
    Drupal\DrupalExtension\Extension:
      drush:
        alias: caw.su.dev

sites:
  extensions:
    Behat\MinkExtension\Extension:
      base_url: https://sites.stanford.edu/caw
    Drupal\DrupalExtension\Extension:
      drush:
        alias: sse.caw
```

To run the tests I now call `behat --profile sites` or `behat --profile local`

**Comment by sherakama** [comment]
imma merge this as it is non-destructive to the other projects.

**Comment by jbickar** [comment]
Except it changes behat.yml.default. But go ahead - invite the Finger of Blame.

**Comment by sherakama** [comment]
PSA during MOA

**Comment by jbickar** [comment]
That said, I'm good with this.

**Pull request merged**
