### PR TITLE
Adding layout tests for people list pages

### PR DESCRIPTION
**Pull request by cjwest**

### CODE REVIEW

**Comment by jbickar** [comment]
Is there a specific branch of stanford_person that this needs to be tested against, or have those changes been merged in to 7.x-4.x?

**Comment by jbickar** [comment]
These tests fail for me, both against 7.x-4.x, and against 7.x-4.x-BASIC-1416

**Comment by cjwest** [comment]
Yes, these tests are failing. This is due to  outstanding issues:

https://stanfordits.atlassian.net/browse/BASIC-1417
<https://stanfordits.atlassian.net/browse/BASIC-1417>https://stanfordits.atlassian.net/browse/BASIC-1416

________________________________

**Comment by cjwest** [comment]
Thanks!



________________________________

**Pull request merged**
