### PR TITLE
Adding @content and @live tags to Scenarios that look for content and…

### PR DESCRIPTION
**Pull request by jbickar**
… can be run on a live site.

@sherakama take a look. I wonder if we should fine-tune this further and use `@content` for Scenarios that look for default content, and `@live` for Scenarios that look for classes and headings (things that should exist on a production JSA site).

@boznik just FYI.

### CODE REVIEW

**Comment by sherakama** [comment]
I very much like this!

This is a great way to break up the tests and run groups of them. By default everything runs so that is kinda poopy as we won't be able to protect against accidentally running non-destructive tests. We can try to solve that problem later. The content one is a little ambiguous as most of the tests I write create the content to test instead of looking for a specific page. I'm not sure there is a scenario where would would just want to test to make sure the pages are there.

The scenarios I can see are:
1.[Non-destructive] Just deployed for client. Need to test that everything is in its place and functionality works without changing anything permanently. 
2.[Destructive] Just built a site for testing purposes. Need to test that everything is in place and functionality works. Destructive tests ok.
3. [Non-destructive] Site is live and went through an upgrade, launch, or migration. Need to test that everything still works with core and site specific tests.
4. ???

Perhaps we should take the time change everything to non-destructive tests or create a tool that reverts back to the original after the tests have run. It seems like that would save us from headache(s) down the road. That could be a good rule for the team to practice.

Any other scenarios you can think of?

**Comment by jbickar** [comment]
`@content` in my mind would be checking for default content that we deploy as part of js*

Scenarios that create content and then check it (I have a lot of these in the `uat` suite) are fine because the Drupal extension deletes the user and the content as part of the teardown.

I am a little leery about labeling anything that changes config as `@live`, _even if it reverts that change_, because what happens if the test fails?

But yeah, I like 1-3, above.

**Comment by sherakama** [comment]
Oh good point. When the test fails it stops.

Let me look at behat 3 and see if there is anything new that can get us further down the road.

**Comment by jbickar** [comment]
Don't let that stop you from merging this PR :)

**Comment by sherakama** [comment]
@jbickar You can haz tags.

**Comment by jbickar** [comment]
I haz tags!

**Pull request merged**
