### PR TITLE
HSDO-700 CAPx Tests

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- CAPx complete tests with submodule tests.

# Urgency
- not critical

# Steps to Test
1. git-crypt unlock
2. run all tests against any site.
3. required stanford_person.

### CODE REVIEW

**Comment by boznik** [comment]
@pookmish , plz resolve conflicts.

**Comment by pookmish** [comment]
Didnt notice that. I just kept changes from both branchs to protect our creds

**Comment by boznik** [comment]
--- Failed scenarios:

    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_auto_nodetitle.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_filters.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_issue_collector.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_ssp.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_tamper.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_webauth.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/stanford_capx.feature:7

7 scenarios (7 failed)
373 steps (67 passed, 7 failed, 299 skipped)
5m36.51s (19.79Mb)

I haven't manually stepped through failed scenarios yet.

**Comment by boznik** [comment]
here are the failed steps:
----------
And I should be on "admin/config/capx/mapper"                             # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)
----------
And I should be on "admin/config/capx/mapper"                                              # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)
----------
Then I should see "capx_issue_collector.js"                  # SWSMinkContext::assertPageContainsText()
      The text "capx_issue_collector.js" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)
----------
And the "capx_ssp" module is enabled                                                                                                                                                            # SWSFeatureContext::theModuleIsEnabled()
      [error]  No release history was found for the requested project (stanford_ssp). 
       [error]  Module capx_ssp cannot be enabled because it depends on the following modules which could not be found: stanford_ssp 
       (RuntimeException)
----------
And I should be on "admin/config/capx/mapper"                                                                                             # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)
----------
And the "capx_webauth" module is enabled                                                                                                                                    # SWSFeatureContext::theModuleIsEnabled()
      [error]  No release history was found for the requested project (webauth). 
       [error]  Module capx_webauth cannot be enabled because it depends on the following modules which could not be found: webauth 
       (RuntimeException)
----------
And I should see the link "Synchronization settings" in the "Content" region                                               # SWSMinkContext::assertLinkRegion()
      No link to "Synchronization settings" in the "Content" region on the page http://local.jsa/admin/config/capx/settings (Exception)
----------

**Comment by pookmish** [comment]
I just made some minor tweaks but these should work on the most recent 7.x-3.x branch of capx. 

>7 scenarios (7 passed)
>373 steps (373 passed)

Having some issues with git-crypt now. Not sure if you might be able to help there. I keep getting 
`git-crypt: error: encrypted file has been tampered with!`
`error: external filter '"git-crypt" smudge' failed 1`

**Comment by boznik** [comment]
git crypt is working for me but i am still getting other errors...
per the discussion in dev chat we'll need to download and enable dependencies on these tests in travis. also, i'm still getting:
--- Failed scenarios:

    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/1st_stanford_capx.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_auto_nodetitle.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_filters.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_capx/capx_tamper.feature:7

7 scenarios (3 passed, 4 failed)
373 steps (121 passed, 4 failed, 248 skipped)
10m0.08s (19.77Mb)

 And I should see the link "Synchronization settings" in the "Content" region                                               # SWSMinkContext::assertLinkRegion()
      No link to "Synchronization settings" in the "Content" region on the page http://local.jsa/admin/config/capx/settings (Exception)

And I should be on "admin/config/capx/mapper"                             # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)

And I should be on "admin/config/capx/mapper"                                              # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)

And I should be on "admin/config/capx/mapper"                                                                                             # SWSMinkContext::assertPageAddress()
      Current page is "/admin/config/capx/mapper/new", but "/admin/config/capx/mapper" expected. (Behat\Mink\Exception\ExpectationException)

**Pull request merged**
