### PR TITLE
SOE-2685: added tests for the related mag. article to department land…

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary
- This replaces the test for the news block on the department landing pages with the test for the related magazine article block.

# Needed By (5/4/2018)
- Sprint end, although it would be nice to have for testing the new release.

# Criticality
- Updates to reflect changes on _Prod_.
- Housekeeping

# Steps to Test
- Switch to this branch
- Navigate to the _Engineering_ directory
- Run the *live* test suite on _Stage_ or a clone of _Stage_.
`../../bin/behat -p sites-jse-soe-stage -s live features `

# Affects 
- SoE (School of Engineering website)

# Associated Issues and/or People
## Related JIRA ticket(s)
https://stanfordits.atlassian.net/browse/SOE-2685

## Folks to notify
@kerri-augenstein 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by minorwm — CHANGES_REQUESTED** [review]
Huston we have a problem :) 

Then I should see 1 or more ".view-stanford-page-top-banner" elements     # SWSFeatureContext::iShouldSeeOrMoreElements()
      0 ".view-stanford-page-top-banner" elements found when there should be a minimum of 1. (Behat\Mink\Exception\ExpectationException)

--- Failed scenarios:

    features/AA_landing_page.feature:7
    features/about_landing_page.feature:7
    features/admission_and_aid_landing_page.feature:7
    features/alumni_landing_page.feature:7
    features/BioE_landing_page.feature:7
    features/CEE_landing_page.feature:7
    features/ChemE_landing_page.feature:7
    features/CS_landing_page.feature:7
    features/EE_landing_page.feature:7
    features/engineering_diversity_landing_page.feature:7
    features/engineering_homepage.feature:7
    features/faculty_and_research_landing_page.feature:7
    features/get_involved_landing_page.feature:7
    features/ME_landing_page.feature:7
    features/MSandE_landing_page.feature:7
    features/MSE_landing_page.feature:7
    features/SoE_future_landing_page.feature:7
    features/students_and_academics_landing_page.feature:7
    features/student_experience_landing_page.feature:7

253 scenarios (234 passed, 19 failed)
1655 steps (1578 passed, 19 failed, 58 skipped)
41m39.15s (12.02Mb)

**Comment by cjwest** [comment]
Huh.

@minorwm, 
1) what site did you use for testing?
2) Can you tell me what actually happened and where it failed?

**Comment by cjwest** [comment]
We need to create tests to accommodate our changes to the banner images on Stanford Pages. 

```
 @safe
  Scenario: Verify users can view the top banner                              # features/AA_landing_page.feature:7
    Given I am on "faculty-research/departments/aeronautics-astronautics"     # SWSMinkContext::visit()
    Then I should see the "img" element in the "Top Full Width" region        # Drupal\DrupalExtension\Context\MarkupContext::assertRegionElement()
    Then I should see 1 or more ".view-stanford-page-top-banner" elements     # SWSFeatureContext::iShouldSeeOrMoreElements()
      0 ".view-stanford-page-top-banner" elements found when there should be a minimum of 1. (Behat\Mink\Exception\ExpectationException)
```

**Comment by cjwest** [comment]
This was moved to:
https://github.com/SU-SWS/linky_clicky/pull/197

**Pull request closed without merging**
