### PR TITLE
New BAM Feature that works.

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- The old Backup and Migrate Feature sucked. This one doesn't.

# Needed By (Date)
- Would be nice to have for tomorrow (3.7) for `people1` testing, but we also can just test on this branch.

# Urgency
- Fixes a broken test.

# Steps to Test

1. Start with a fresh install of the `stanford` profile. Ensure that you don't have any stray files in your `sites/default/files/` directory.
2. Run this Feature.
3. See that it passes, _and_ that no backup files are left behind at `admin/config/system/backup_migrate/backups` 

# Affected Projects or Products
- Mostly testing for `Stanford-Drupal-Profile`

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/CI-10
- Other PRs
- Anyone who should be notified? @sherakama, @cjwest, @pookmish, and @boznik might be interested in this.

### CODE REVIEW

**Comment by kbrownell** [comment]
Passes for me locally:
```
1 scenario (1 passed)
69 steps (69 passed)
0m40.02s (16.75Mb)
```

**Comment by jbickar** [comment]
Don't merge yet, I'm still struggling with what to do with webauth

**Comment by jbickar** [comment]
OK, @kbrownell, this is ready to test now. I fixed the webauth issues.

**Comment by kbrownell** [comment]
Success: https://travis-ci.org/SU-SWS/Stanford-Drupal-Profile/builds/209572499.
You were spot on, php runserver was struggling with periods in the file path url's.

**Pull request merged**
