### PR TITLE
Basic 1551

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for Review

Steps to test:
1. Install the latest stanford_conference feature in to your favorite testing site
2. Symlink the `/includes/features/stanford_conference/stanford_conference.feature` in to the testing suite of your choice. eg: `ln -s /includes/features/stanford_conference/stanford_conference.feature /jsa/features/stanford_conference.feature`
3. Run tests using the 'all' suite

If you upgrade to field_collection beta-11 and add patch #7 as seen in the following pull request, you may run and re-run this test without path aliases sticking around: https://github.com/SU-SWS/stanford-jumpstart-deployer/pull/64

### CODE REVIEW

**Comment by sherakama** [comment]
@cjwest FYI

**Comment by cjwest** [comment]
Hmmm... Step 1 says to "Install the latest stanford_courses feature." Was that supposed to be stanford_conference feature? :wink:

**Comment by sherakama** [comment]
Good catch. That was my brain playing tricks on me again.

**Comment by jbickar** [comment]
So I should expect step 4 to be "stanford_conference Feature runs as expected"?

**Comment by sherakama** [comment]
Yes, now conflicts with this... let me fix up.

**Comment by boznik** [comment]
@sherakama ,

getting lots of the same error:
No release history was found for the requested project.

**Comment by boznik** [comment]
this looks good. all behat tests passed.

**Comment by sherakama** [comment]
woot!

**Pull request merged**
