### PR TITLE
HSDO-711 Events tests

### PR DESCRIPTION
**Pull request by pookmish**
# Ready For Review
not tested on Travis.ci

### CODE REVIEW

**Comment by sherakama** [comment]
--- Failed scenarios:

```
/stanford_events_importer/stanford_events_export.feature:7
/stanford_events_importer/stanford_events_views.feature:7
/stanford_events_importer/stanford_event_and_deadline_calendar.feature:7
/stanford_events_importer/stanford_event_and_deadline_calendar.feature:14
/stanford_events_importer/stanford_event_and_deadline_calendar.feature:22
```

I will come back and review this one.

**Comment by pookmish** [comment]
Try testing again. i added some cache clear and module enable for each individual test. just in case :)

**Comment by sherakama** [comment]
11 scenarios (11 passed)
137 steps (137 passed)

**Comment by sherakama** [comment]
I removed the "module enabled" steps and enabled them myself.

**Pull request merged**
