### PR TITLE
JSPLUS features tests added to jsplus product

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for review

### CODE REVIEW

**Comment by cjwest** [comment]
What harvest category/jira ticket do I use?

**Comment by sherakama** [comment]
Stanford Sites Jumpstart
Web Development

-S

**Comment by cjwest** [comment]
This test failed. It needs a "live" rather than "prod" tag:

  @api @prod @safe
  Scenario: Stanford MetaTag NoBots                         # /Users/cjwest/Documents/htdocs/behat/linky_clicky/includes/features/SU-SWS/stanford_metatag_nobots/stanford_metatag_nobots.feature:14
    And the cache has been cleared                          # SWSDrupalContext::assertCacheClear()
    And I am on the homepage                                # SWSMinkContext::iAmOnHomepage()
    Then the response header should not have "X-Robots-Tag" # SWSFeatureContext::theResponseHeaderShouldNotHave()
      The HTTP header "X-Robots-Tag" is set to: noindex,nofollow,noarchive. (Exception)

**Comment by cjwest** [comment]
This test failed. It's looking for the "Search" block in the "Second sidebar." It should be looking in the "First sidebar"

@safe @deploy
  Scenario: Test enabled contexts for block existance in region                                                  # features/stanford_jumpstart_plus/stanford_jumpstart_plus_layouts/stanford_jumpstart_plus_layouts.feature:33
    Given I am on the homepage                                                                                   # SWSMinkContext::iAmOnHomepage()
    Then I should see 1 "#block-menu-block-stanford-jumpstart-layouts-1" element in the "Main Navigation" region # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I should see 1 "#block-search-form" element in the "Search Box" region                                  # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I should see 1 "#block-bean-jumpstart-footer-social-media-0" element in the "Footer" region             # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I should see 1 "#block-bean-jumpstart-footer-contact-block" element in the "Footer" region              # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I should see 1 "#block-bean-optional-footer-block" element in the "Footer" region                       # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I should see 1 "#block-menu-menu-related-links" element in the "Footer" region                          # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I am on "about"                                                                                         # SWSMinkContext::visit()
    Then I should see 1 "#block-menu-block-stanford-jumpstart-layouts-2" element in the "First sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I am on "events/month/2016-01"                                                                          # SWSMinkContext::visit()
    Then I should see 1 "#block-views-934c9b9d8d2d2f2b37f050dcd3bba83c" element in the "Second sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I am on "events/month/2016-01-01"                                                                       # SWSMinkContext::visit()
    Then I should see 1 "#block-views-934c9b9d8d2d2f2b37f050dcd3bba83c" element in the "Second sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Given I am on "events/upcoming-events"                                                                       # SWSMinkContext::visit()
    Then I click on the element with css selector ".view-stanford-events-views .event-title a"                   # SWSFeatureContext::iClickOnTheElementWithCSSSelector()
    Then I should see 1 "#block-views-934c9b9d8d2d2f2b37f050dcd3bba83c" element in the "Second sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I am on "events/past-events"                                                                            # SWSMinkContext::visit()
    Then I should see 1 "#block-views-ad215e0528148b386833fa3db1f3b7dc" element in the "Second sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()
      0 "#block-views-ad215e0528148b386833fa3db1f3b7dc" elements found when there should be 1. (Behat\Mink\Exception\ExpectationException)
    Then I should see 1 "#block-views-934c9b9d8d2d2f2b37f050dcd3bba83c" element in the "First sidebar" region    # SWSFeatureContext::iShouldSeeElementsInTheRegion()
    Then I am on "events/upcoming-events"                                                                        # SWSMinkContext::visit()
    Then I should see 1 "#block-views-934c9b9d8d2d2f2b37f050dcd3bba83c" element in the "Second sidebar" region   # SWSFeatureContext::iShouldSeeElementsInTheRegion()

**Comment by cjwest** [comment]
@sherakama , please check my comments

**Comment by cjwest** [comment]
When I run suite=dev, I'm getting errors when logging in as admin.

`@api @javascript @content @dev
  Scenario: Add Stanford Page                                                                                        # /Users/cjwest/Documents/htdocs/behat/linky_clicky/includes/features/SU-SWS/stanford_page/stanford_page.feature:27
    Given I am logged in as a user with the "administrator" role                                                     # SWSDrupalContext::assertAuthenticatedByRole()
      element not visible
        (Session info: chrome=49.0.2623.110)
        (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 29 milliseconds
      Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
      System info: host: 'ITS-C02PV55XFVH8', ip: '10.34.192.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/vq/_zxpsbm57wqbhk1fqbn47dy80000gp/T/.org.chromium.Chromium.2enB78}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
      Session ID: 24977bd6ad8c34639a203032914257e6 (WebDriver\Exception\ElementNotVisible)
    When I wait for the Site Actions drop down to appear                                                             # SWSFeatureContext::iWaitForTheSiteActionsDropDownToAppear()`

**Pull request merged**
