### PR TITLE
SITES-528: Behat test changes for JSV on socorro build

### PR DESCRIPTION
**Pull request by sherakama**
# ALMOST - READY FOR REVIEW

# Summary
- Green light the JSV build of Socorro

# Needed By (Date)
- End of June

# Urgency
- Medium

# Steps to Test

1. Check out the latest of the socorro branch
2. Run composer install
3. Start lando `lando start`
4. Install a fresh build of JSV `lando drush si stanford_sites_jumpstart install_configure_form.itasks_extra_tasks=acsf -y` 
5. Check out this branch of linky_clicky in `/vendor/su-sws/linky_clicky`
6. Run JSV behat tests `lando behat --config=/app/tests/behat/jsv/behat.yml -s all`
7. Wait about 60 minutes for the full suite to run
8. View results in terminal or at `tests.cardinald7.sws`

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
At `lando drush si stanford_sites_jumpstart install_configure_form.itasks_extra_tasks=acsf -y`:

```
Exception: Required modules: Required modules not found.                                                                                                                                                                                             [error]

The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as <em>sites/all/modules</em>. Missing modules: <span class="admin-missing">Stanford_bean_types_icon_grid</span> in
/app/docroot/includes/install.core.inc:773
Stack trace:
#0 /app/docroot/profiles/stanford_sites_jumpstart/includes/iTasks.php(188): install_verify_requirements(Array)
```

I merged the latest socorro into my `SITES-540-saml-metadata` branch. I see a `docroot/sites/all/modules/stanford/stanford_bean_types/modules/stanford_icon_grid/` but no `stanford_bean_types_icon_grid`.

**Comment by jbickar** [comment]
```
% lando behat --config=/app/tests/behat/jsv/behat.yml -s all
Unknown arguments: config, s, behat
```

**Comment by jbickar** [comment]
Might want to consider this for Lando/Behat:
- https://github.com/elvetemedve/behat-screenshot
- https://github.com/acquia/blt/blob/5d0079de5bd0972cda13dbeccfdddf1ef54f4cac/template/tests/behat/behat.yml#L19

**Comment by sherakama** [comment]
This looks awesome. Yes, please add.

There is way to get the chromedriver to record video and possibly show the work in progress as well but I did not get that far.

**Comment by jbickar** [comment]
You can thank @kbrownell for that pointer.

**Pull request merged**
