### PR TITLE
Rename misnamed directory and feature

### PR DESCRIPTION
**Pull request by jbickar**

### CODE REVIEW

**Comment by sherakama** [comment]
Seems legit. 

I did a quick look around and I did not find anything that was sym-linking to that directory from somewhere else. 

If you have also confirmed that no other symlinks need to change then it is ok to merge by me.

**Comment by jbickar** [comment]
Good idear.

**Comment by jbickar** [comment]
```
spr-jbickar: ~/Documents/working/linky_clicky$ find ./ -type l | grep helper
.//products/jse/features/stanford_sites_helper
.//products/jslbre/features/stanford_sites_helper
.//products/jsvpsa/features/stanford_sites_helper
```

**Comment by jbickar** [comment]
@cjwest FYI

**Comment by cjwest** [comment]
Thanks @jbickar

**Pull request merged**
